# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IndexWindow(object):
    def setupUi(self, IndexWindow):
        IndexWindow.setObjectName("IndexWindow")
        IndexWindow.resize(631, 516)
        self.centralwidget = QtWidgets.QWidget(IndexWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 381, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.selector_language = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.selector_language.setObjectName("selector_language")
        self.horizontalLayout.addWidget(self.selector_language)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 381, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_file = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_file.setObjectName("button_file")
        self.horizontalLayout_2.addWidget(self.button_file)
        self.button_dir = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_dir.setObjectName("button_dir")
        self.horizontalLayout_2.addWidget(self.button_dir)
        self.button_start = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_2.addWidget(self.button_start)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(30, 150, 571, 251))
        self.tableView.setObjectName("tableView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 410, 571, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_code_num = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_code_num.setText("")
        self.label_code_num.setObjectName("label_code_num")
        self.gridLayout.addWidget(self.label_code_num, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_comment_num = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_comment_num.setText("")
        self.label_comment_num.setObjectName("label_comment_num")
        self.gridLayout.addWidget(self.label_comment_num, 0, 3, 1, 1)
        self.label_empty_num = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_empty_num.setText("")
        self.label_empty_num.setObjectName("label_empty_num")
        self.gridLayout.addWidget(self.label_empty_num, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_total_num = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_total_num.setText("")
        self.label_total_num.setObjectName("label_total_num")
        self.gridLayout.addWidget(self.label_total_num, 1, 3, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 120, 571, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_address = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_address.setText("")
        self.label_address.setObjectName("label_address")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_address)
        IndexWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IndexWindow)
        self.statusbar.setObjectName("statusbar")
        IndexWindow.setStatusBar(self.statusbar)

        self.retranslateUi(IndexWindow)
        QtCore.QMetaObject.connectSlotsByName(IndexWindow)

    def retranslateUi(self, IndexWindow):
        _translate = QtCore.QCoreApplication.translate
        IndexWindow.setWindowTitle(_translate("IndexWindow", "MainWindow"))
        self.label.setText(_translate("IndexWindow", "请先选择程序语言"))
        self.button_file.setText(_translate("IndexWindow", "选择文件"))
        self.button_dir.setText(_translate("IndexWindow", "选择目录"))
        self.button_start.setText(_translate("IndexWindow", "统计行数"))
        self.label_2.setText(_translate("IndexWindow", "空  行"))
        self.label_3.setText(_translate("IndexWindow", "代码行"))
        self.label_5.setText(_translate("IndexWindow", "注释行"))
        self.label_8.setText(_translate("IndexWindow", "总行数"))
        self.label_4.setText(_translate("IndexWindow", "路径：  "))

